version: "1.0.0"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: code_sync:2.0
    command: npm start
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      API_KEY: randomKey
